
app.config(function($stateProvider){
    $stateProvider
    .state('home',{
        url:'/',
         views:{
             '':{
                templateUrl:'template/home.html'
             },
            'contents@home':{
                template:'<p>这是广告</p>'
            }
        }
    })
    .state('home.inbox',{
        url:'^/inbox',
        views:{
            'contents':{
                templateUrl:'template/inboxPage.html'
            }
        }
    })
    .state('home.inbox.letter',{
            url:"/:letterId",
            views:{
                'letterContent':{
                    templateUrl:'template/letterContent.html',
                    controller:'contentController'
                }
            }
    })
    .state('home.outbox',{
        url:'^/outbox',
        views:{
            'contents':{
                templateUrl:'template/outboxPage.html'
            }
        }
    })
    .state('home.writePage',{
        url:'^/writePage',
        views:{
            'contents':{
                templateUrl:'template/writePage.html',
                controller:'writeController'
            }
        }
    })
});
app.run(function($state){
    $state.go('home');
});