
app.config(function($stateProvider){
    $stateProvider
    .state('home',{
        url:'/',
         views:{
            'header':{
                templateUrl:'template/header.html'
            },
            'nav':{
                templateUrl:'template/nav.html'
            }
        }
    })
    .state('inbox',{
        url:'/inbox',
        views:{
            'header':{
                templateUrl:'template/header.html'
            },
            'nav':{
                templateUrl:'template/nav.html'
            },
            'contents':{
                templateUrl:'template/inboxPage.html'
            }
        }
    })
    .state('inbox.letterA',{
        url:'/letterA',
        views:{
            'header':{
                templateUrl:'template/header.html'
            },
            'nav':{
                templateUrl:'template/nav.html'
            },
            'contents':{
                templateUrl:'template/letterA.html'
            }
        }
    })
     .state('letterB',{
        url:'/letterB',
        views:{
            'header':{
                templateUrl:'template/header.html'
            },
            'nav':{
                templateUrl:'template/nav.html'
            },
            'contents':{
                templateUrl:'template/letterB.html'
            }
        }
    })
    .state('outbox',{
        url:'/outbox', 
        views:{
            'header':{
                templateUrl:'template/header.html'
            },
            'nav':{
                templateUrl:'template/nav.html'
            },
            'contents':{
                templateUrl:'template/outboxPage.html'
            }
        }
    })
});
app.run(function($state){
    $state.go('home');
});